services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ecentral\CantoSaasFal\:
    resource: '../Classes/*'

  Ecentral\CantoSaasFal\Hooks\DataHandlerHooks:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Ecentral\CantoSaasFal\Resource\Repository\CantoRepository:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Ecentral\CantoSaasFal\Resource\Metadata\Extractor:
    public: true

  Ecentral\CantoSaasFal\Resource\Processing\CantoPreviewProcessor:
    public: true

  Ecentral\CantoSaasFal\Resource\Processing\CantoMdcProcessor:
    public: true

  Ecentral\CantoSaasFal\Controller\Backend\CantoAssetBrowserController:
    public: true

  Ecentral\CantoSaasFal\Resource\MdcUrlGenerator:
    public: true

  Ecentral\CantoSaasFal\Resource\Repository\CantoAlbumRepository:
    arguments:
      - 'sys_file_canto_album'
      - '@TYPO3\CMS\Core\Database\ConnectionPool'

  Ecentral\CantoSaasFal\Command\WarmupCantoCache:
    calls:
      - injectStorageRepository: ['@TYPO3\CMS\Core\Resource\StorageRepository']
      - injectCantoFolderCache: ['@cache.canto_folder']
    tags:
      - name: 'console.command'
        command: 'canto:warmupcache'

  Ecentral\CantoSaasFal\Command\UpdateMetadataAssetsCommand:
    tags:
      - name: 'console.command'
        command: 'canto:updatemetadataassets'

  Ecentral\CantoSaasFal\Resource\EventListener\HandleMultipleFolders:
    tags:
      - name: event.listener
        identifier: updateFoldersAfterFileAddedToIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent
        method: afterFileAddedToIndexEvent
      - name: event.listener
        identifier: updateFoldersAfterFileUpdatedInIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent
        method: afterFileUpdatedInIndexEvent

  Ecentral\CantoSaasFal\Resource\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        identifier: generatePublicUrlForMdcFiles
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  Ecentral\CantoSaasFal\Resource\EventListener\ForceJpgPreviewImage:
    tags:
      - name: event.listener
        identifier: forceCantoJpegPreview
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  Ecentral\CantoSaasFal\Resource\EventListener\MetadataWebhookEventListener:
    tags:
      - name: event.listener
        identifier: metadataWebhookEventListener
        event: Ecentral\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Ecentral\CantoSaasFal\Resource\EventListener\NewAssetVersionWebhookEventListener:
    tags:
      - name: event.listener
        identifier: newAssetVersionWebhookEventListener
        event: Ecentral\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Ecentral\CantoSaasFal\Resource\EventListener\DeleteAssetWebhookEventListener:
    tags:
      - name: event.listener
        identifier: deleteAssetWebhookEventListener
        event: Ecentral\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Ecentral\CantoSaasFal\Resource\EventListener\BeforeFileProcessingEventListener:
    arguments:
      - "@Ecentral\\CantoSaasFal\\Resource\\Repository\\CantoRepository"
      - "@TYPO3\\CMS\\Core\\Resource\\ProcessedFileRepository"
      - "@Ecentral\\CantoSaasFal\\Resource\\MdcUrlGenerator"
    tags:
      - name: event.listener
        identifier: cantoMdcProcessingFileEnricher
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  cache.canto_folder:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['canto_saas_fal_folder']

  cache.canto_file:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'canto_saas_fal_file' ]
