services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ecentral\CantoSaasFal\:
    resource: '../Classes/*'

  Ecentral\CantoSaasFal\Resource\Canto\CantoProxyClient:
    autowire: false

  Ecentral\CantoSaasFal\Hooks\DataHandlerHooks:
    autowire: false
    public: true
    arguments:
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Ecentral\CantoSaasFal\Resource\Repository\CantoRepository:
    autowire: false
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Ecentral\CantoSaasFal\Resource\Metadata\Extractor:
    public: true

  Ecentral\CantoSaasFal\Resource\Processing\CantoPreviewProcessor:
    public: true

  Ecentral\CantoSaasFal\Resource\Repository\CantoAlbumRepository:
    autowire: false
    arguments:
      - 'sys_file_canto_album'
      - '@TYPO3\CMS\Core\Database\ConnectionPool'

  Ecentral\CantoSaasFal\Resource\EventListener\HandleMultipleFolders:
    tags:
      - name: event.listener
        identifier: updateFoldersAfterFileAddedToIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent
        method: afterFileAddedToIndexEvent
      - name: event.listener
        identifier: updateFoldersAfterFileUpdatedInIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent
        method: afterFileUpdatedInIndexEvent

  Ecentral\CantoSaasFal\Resource\EventListener\ForceJpgPreviewImage:
    tags:
      - name: event.listener
        identifier: forceCantoJpegPreview
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  cache.canto_folder:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['canto_saas_fal_folder']

  cache.canto_file:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'canto_saas_fal_file' ]
