name: 🔎 code quality

on: [ push, pull_request ]

jobs:
    compute:
        uses: ./.github/workflows/compute.yml

    fix:
        name: PHP CS Fixer

        needs: [ compute ]

        env:
            php: ${{ fromJson(needs.compute.outputs.php-single) }}

        runs-on: ${{ fromJson(needs.compute.outputs.os-single) }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Store Composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache/restore@v4
                id: restore-composer-cache
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-check-fix-${{ env.php }}
                    restore-keys: |
                        ${{ runner.os }}-composer-check-fix-
                        ${{ runner.os }}-composer-check-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version ${{ env.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.php }}
                    extensions: xdebug, mbstring, posix
                    tools: composer:v2

            -   name: Environment Check
                run: |
                    php -v
                    php -m
                    composer --version

            -   name: Composer install
                run: composer update --no-interaction

            -   name: Save composer cache
                uses: actions/cache/save@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ steps.restore-composer-cache.outputs.cache-primary-key }}

            -   name: Run PHP CS Fixer
                run: php .Build/bin/php-cs-fixer check --diff --no-interaction --show-progress=none
